# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --project --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Symbolics"); Pkg.test("Symbolics"; coverage=true)'

after_success:
  - julia -e 'using Pkg'
  # push coverage results to Coveralls
  - julia -e 'import Symbolics'
  - julia -e 'joinpath(dirname(pathof(Symbolics)), ".."); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Coverage; Codecov.submit(Codecov.process_folder())'
  # # Documentation
  # - julia -e 'Pkg.add("Documenter")'
  # - julia -e 'include(joinpath(dirname(pathof(Symbolics)), "../docs", "make.jl"))'
